name: Cypress Tests

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2 # use the explicit version number
        with:
          build: npm run build
          start: npm start
